name: CI/CD Workflow
on:
    push:
        branches: [main] 
    pull_request: 
        branches: [main]

# Jobs
jobs:
    lint:
        name: ESLint - Sin errores
        runs-on: ubuntu-latest
        steps:
            - name: Clonar repositorio
              uses: actions/checkout@v4

            - name: Configurar Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Instalar dependencias
              run: npm install
            
            - name: Ejecutar lint del codigo (sin errores)
              run: npm run lint
    test-and-coverage:
        name: Tests with Coverage ≥85%
        runs-on: ubuntu-latest
        steps:
            - name: Clonar repositorio
              uses: actions/checkout@v4

            - name: Configurar Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Instalar dependencias
              run: npm install
            
            - name: Ejecutar pruebas con cobertura ≥85%
              run: npm run test:ci

            - name: Verificar cobertura mínima
              run: |
                echo "Verificando cobertura mínima ≥85% (líneas y ramas)"
                # Jest ya verifica los thresholds configurados en package.json

    build:
        name: Build Application
        runs-on: ubuntu-latest
        needs: [lint, test-and-coverage]
        steps:
            - name: Clonar repositorio
              uses: actions/checkout@v4

            - name: Configurar Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Instalar dependencias
              run: npm ci

            - name: Build exitoso
              run: echo "Build completado exitosamente"
